# include:
#   - ./app/scraper.yaml
services:
  fastapi:
    build: ./
    ports:
      - "8123:8123"
    volumes:
      - shared_data:/app/data

  scraper:
    build: ./app
    volumes:
      - shared_data:/app/data
    secrets:
      - .env
      # - env_secrets
    # env_file:
    #   - .env
    # environment:
    #   GEOAPIFY_API_KEY: /run/secrets/env_secrets

volumes:
  shared_data:

secrets:
  # env_secrets:
  .env:
    file: ./app/.env
  # GEOAPIFY_API_KEY:
  #   environment: GEOAPIFY_API_KEY