# include:
#   - ./app/scraper.yaml
services:
  fastapi:
    build: ./
    ports:
      - "8123:8123"
    volumes:
      - shared_data:/code/shared
    depends_on:
      scraper:
        condition: service_started

  scraper:
    build: ./app
    volumes:
      - shared_data:/code/shared
    secrets:
      - env_secrets
    # env_file:
    #   - .env
    # environment:
    #   GEOAPIFY_API_KEY: /run/secrets/env_secrets

volumes:
  shared_data:

secrets:
  env_secrets:
    file: ./app/.env
  # GEOAPIFY_API_KEY:
  #   environment: GEOAPIFY_API_KEY