# include:
#   - ./app/scraper.yaml
services:
  fastapi:
    build: ./
    ports:
      - "8123:8123"
    volumes:
      - shared_data:/code/shared
    # depends_on:
      # scraper:
        # condition: service_started
      # condition: service_completed_successfully

  scraper:
    build: ./app
    volumes:
      # - shared_data:/code/shared
      - shared_data:/usr/share/geojson
    # depends_on:
    #   fastapi:
    #     condition: service_started
    secrets:
      - env_secrets
    restart: on-failure
  # data_updater: # scheduled job to update the shared geojson data
    # volumes:
      # - shared_data:/usr/share/geojson
    # restart: 5 mins
    # command: docker run --rm -it scraper cp /code/data/data.geojson /usr/share/geojson/data.geojson

volumes:
  shared_data:

secrets:
  env_secrets:
    file: ./app/.env