# include:
#   - ./app/scraper.yaml
services:
  fastapi:
    build: ./
    ports:
      - "8123:8123"
    volumes:
      - shared_data:/code/shared
    depends_on:
      scraper:
        condition: service_started
    # command: cat ./shared/bar.txt
    # command: ls ./shared -a

  scraper:
    build: ./app
    volumes:
      # - shared_data:/code/shared
      - shared_data:/usr/share/geojson
    secrets:
      - env_secrets
    restart: on-failure
    # command: sh ./entrypoint.sh


volumes:
  shared_data:

secrets:
  env_secrets:
    file: ./app/.env