version: '3.8'

services:
  fastapi:
    build: ./
    ports:
      - "8123:8123"
    volumes:
      - shared_data:/app/data

  scraper:
    build: ./app
    volumes:
      - shared_data:/app/data

volumes:
  shared_data: